### ISSUE TITLE
goswagger fails

### ISSUE THREAD

**Issue by regorov** [pinnacleapi/pinnacleapi-documentation#11]
Using goswagger I've tried to generate golang client.
```
[regorov@t460p openapi-specification]$ ./swagger -o log.log generate client --skip-validation -f ./betsapi-oas.yaml
```
fails with message 
```
failed rendering template data for definition: template execution failed for template definition: template: schemavalidator:476:65: executing "schemavalidator" at <.>: wrong type for value; expected string; got bool
```
There are no issues with lines or customer api.

**Comment by pinnacleapi** [comment]
Would it work for you to try generating the client using  https://editor.swagger.io ?

**Comment by regorov** [comment]
I did. It works, but the code generated by goswagger I like more ) please take a look, I've pulled request https://github.com/pinnacleapi/openapi-specification/pull/2
