### ISSUE TITLE
Wrong Status in Fixtures_V1_Get ?

### ISSUE THREAD

**Issue by Fablepongiste** [pinnacleapi/pinnacleapi-documentation#12]
The status information 
```
O = This is the starting status of a game. It means that the lines are open for betting, H = This status indicates that the lines are temporarily unavailable for betting, I = This status indicates that one or more lines have a red circle (lower maximum bet amount)
```

Seems very often incorrect,, for example I while limits are up. 

Will that be I if Moneyline are not opened for a game but spread and total are up already ? 

Should this information not be at the odds level and not at the fixture ?

**Comment by pinnacleapi** [comment]
Indeed, we are slowly moving to a new data model that will allow what you described, though, notion of red circle is getting deprecated. 
Event status is actually deprecated,  please see updated documentation.
