### ISSUE TITLE
How get Minute and HT for game in Live

### ISSUE THREAD

**Issue by DimonAffGod** [pinnacleapi/pinnacleapi-documentation#14]
Hello!

I get live games (liveStatus=1).
How I can get what is the minute of the match now?
How can I find out that now is a break in the match (HT)???

In site, for soccer live events match minute is shown. HT is shown also.

Thanks

**Comment by pinnacleapi** [comment]
Please check https://pinnacleapi.github.io/linesapi#operation/InRunning_V1_Get , cheers
