### ISSUE TITLE
Red / Blue Circle

### ISSUE THREAD

**Issue by Fablepongiste** [pinnacleapi/pinnacleapi-documentation#18]
Is there now a way to get this status for every single bets / markets ? Or to know if limit are at their maximum / will still increase ? 

You mentioned in #12 that this might become possible soon ?

**Comment by pinnacleapi** [comment]
Sorry , we don't have yet the statuses per market and we can't give any ETA. 
With regards to limits,  we provide current market limits, that may be bigger (red) or lower (blue) than default, At the moment, there are no plans to support red/blue indicator in the API, it's only a feature of the Classic View on the website.

**Comment by Fablepongiste** [comment]
Weird that you used to provide something (red circle info in API) but now have removed it without a plan to reinstate it. Means code using it is now useless ;-(

**Comment by pinnacleapi** [comment]
sorry, let me clarify, `/fixtures` still support `status` **I** that indicates if one of the markets on the fixture has lower limits (red circle), but at the moment there are no plans to support this indicator on the market level.
