### ISSUE TITLE
Place spread bet, linedId mandatory?

### ISSUE THREAD

**Issue by irokhes** [pinnacleapi/pinnacleapi-documentation#20]
Hi,

is the scenario when I want to place a spread bet which has altLineId, should I send the lineId as well? or only the altLineId?

Thanks

**Comment by pinnacleapi** [comment]
`lineid` is mandatory in both cases.

**Comment by irokhes** [comment]
Thanks!
 Another question about mandatory params, in the case of TOTALS_POINTS
should I send the 'team' param?

Do you have a sandbox environment?

Thanks a lot

**Comment by pinnacleapi** [comment]
`team` is not needed, but `side` is. Sorry, we don't have sandbox environment .
