### ISSUE TITLE
Place Bet Line changed

### ISSUE THREAD

**Issue by irokhes** [pinnacleapi/pinnacleapi-documentation#21]
When I place a bet and I get a LINE_CHANGED error I try again (with a 1 second delay) a few times (max 5) but I'm getting the same error. Is that normal? should I wait longer than that?...

Thanks

**Comment by pinnacleapi** [comment]
When you get the `LINE_CHANGED` error, you would need to fetch again the latest price from `\odds` or `\line`

**Comment by irokhes** [comment]
I do get the odds from 
`https://api.pinnacle.com/v1/odds?oddsFormat=Decimal&eventIds[]=${eventId}`
before every try but I'm still getting the LINE_CHANGED error.
Is that the right method to call?

**Comment by pinnacleapi** [comment]
yes, but you would need to use delta calls and the snapshots are being cached , for more details see 
https://github.com/pinnacleapi/pinnacleapi-documentation/blob/master/FAQ.md#how-to-get-odds-changes
https://github.com/pinnacleapi/pinnacleapi-documentation/blob/master/FairUsePolicy.md
