### ISSUE TITLE
Place bet RESUBMIT_REQUEST error response

### ISSUE THREAD

**Issue by irokhes** [pinnacleapi/pinnacleapi-documentation#22]
When I get this error trying to place a straight bet, how do I make a valid bet? is it the same situation as LINE_CHANGED? so I have to get the odds again and resubmit the bet?

**Comment by pinnacleapi** [comment]
You can retry and send the same place bet  request again, but it's very likely that the line will change after such an error, so better to get the latest line always after this error .

**Comment by irokhes** [comment]
I'm looking at my logs and I see the following error

```
name: 'StatusCodeError',
statusCode: 400,
message: '400 - {"code":"RESUBMIT_REQUEST","message":"Place bet failed after 2 retries."}',
error: 
{ code: 'RESUBMIT_REQUEST',
message: 'Place bet failed after 2 retries.' },
```

Reading the documentation I understood the RESUBMIT_REQUEST errorCode comes with http status 200 but in this case is 400. It's also confusing the `Place bet failed after 2 retries.` message because I seen there is only 1 try to place that bet.

**Comment by pinnacleapi** [comment]
You are right, documentation is corrected now. Thanks for bringing this to our attention.
Message itself reflects the number of internal retries.

**Comment by irokhes** [comment]
Oh great! thanks for the clarification!
