### ISSUE TITLE
Tennis Scoring

### ISSUE THREAD

**Issue by JohnnyBlazzing** [pinnacleapi/pinnacleapi-documentation#23]
I have noticed the scoring for tennis games is a total of games won, which means the winner does not necessarily has the highest points.

I think for a Tennis Match bet... the score should be the no# of sets won, as the winner is the player with the most sets - not the most game points. So womens would have a max value of 2, and mens 3.

And for game bets eg ' Game 13 of Set 1', the scores should be for the game with values 0,15,30,40,50. not the number of games they have won in the match so far.

The only tennis bets where number of games do count is Set bets, Eg ' To Win Set 2' so keep this as is.

**Comment by JohnnyBlazzing** [comment]
Just an addition, for the Set bets. Should just be the games won for the set. So this should be updated too. 
The max score for a set game should be 7, currently for a set 2 game score you have sum of games from set 1 and 2.

**Comment by pinnacleapi** [comment]
Thanks for pointing out. We provide the score in sets as well, just that the feature was missing in the docs, but it's been updated now https://github.com/pinnacleapi/openapi-specification/commit/0c6b6a8ec89c2d1dc1f1a982b26c95767dd31a77
We'll review your feedback on the score resulting, in the meantime when you check the score, do you take into account the `period`?

**Comment by JohnnyBlazzing** [comment]
All the periods listed for a game or a set bet only have a single period 0.
I'm guessing tennis doesn't fit the usual sport format. If you can tidy
this up for me that would be great. Definitely would be more intuitive to
everyone using it.

**Comment by pinnacleapi** [comment]
wrt to resulting of the "Game X of Set Y"  events, this is indeed an issue that will be addresses in the future but at moment we can’t give any  estimates when.
 
If it can help, we only offer moneyline market on these events  and such event is resulted with the set score set to 1 for the player who won the game.
