### ISSUE TITLE
Events with period 1 which should be period 0

### ISSUE THREAD

**Issue by sattva1** [pinnacleapi/pinnacleapi-documentation#25]
Hi,

We've noticed that certain e-sports events provided by the lines API (/v1/odds) contain period 1 only while it actually represents the whole match (i.e. should be period 0 under the API specification). This behavior by itself wouldn't be much of a problem, however other e-sports events happen to have period 1 lines listed at first and then a few hours (or even a day) later other periods added as well. This means such period 1 lines does not represent the whole match, and there is no way to tell this in advance until other periods are listed.

The described behavior is highly ambiguous and clearly violates the API specification which states that whole match is represented by period 0. Unless there is in fact a way to tell an event will remain "period 1 only", can this be fixed?

Here are a few recent event IDs from the first category (with period 1 == whole match):
1000741520
996905808
1000360229
1001616096
1000741505
1000360235
996862635
1000360239
1001616128
996862674
1001185858
1000741535
1000360232
1001185870
1001431393

And a few event IDs from the second category (with period 1 only listed at first and other periods added later):
1002059700
1001641650
1002059704
1002059699
1001641565
1001641783
1001641805
1001641760

**Comment by pinnacleapi** [comment]
This is be fixed now, with the exception that for Best of 1 event prices may appear under Period 0 or 1.
