### ISSUE TITLE
Pinnacle / PS3838 should be the same

### ISSUE THREAD

**Issue by Eliakos** [pinnacleapi/pinnacleapi-documentation#26]
Hello,

https://www.ps3838.com/en/euro/ is owned by Pinnacle and they talk about the API here  
https://www.ps3838.com/static/index.php/en-us/help/api-user-guide-en-us#getting-started which is a little dated (2016).

The question is : does the C# Wrapper for the PinnacleSports API (https://github.com/harveysburger/pinnaclewrapper) works with ps3838 too ?

Kind Regards

**Comment by pinnacleapi** [comment]
Sorry for the late answer, we are not maintaining C# Wrapper for the PinnacleSports API. A guess would be that it should match for the most part.
