### ISSUE TITLE
Postman : Could not get any response

### ISSUE THREAD

**Issue by Eliakos** [pinnacleapi/pinnacleapi-documentation#27]
Hello,

I give Pinnacle API a try with Postman.
I use ps3838.com website which belongs to Pinnacle and is said to be the same API

I tested with success calls like login https://api.ps3838.com/, get sports https://api.ps3838.com/v1/sports, get client balance https://api.ps3838.com/v1/client/balance.

Then i tried calls like get fixtures https:// api.ps3838.com/v1/fixtures?sportId=29, get leagues
https:// api.ps3838.com/v1/leagues?sportId=3, get odds https:// api.ps3838.com/v1/odds?sportId=3

and as a result i get :
Could not get any response
There was an error connecting to https:// api.ps3838.com/v1/odds?sportId=3.
Why this might have happened:
- The server couldn't send a response: Ensure that the backend is working properly
- Self-signed SSL certificates are being blocked: Fix this by turning off 'SSL certificate verification' in Settings > General
- Proxy configured incorrectly Ensure that proxy is configured correctly in Settings > Proxy
- Request timeout: Change request timeout in Settings > General 

Apparently it's not about :
- server response, self-signed ssl or proxy configuration as calls like login or get sports are working
- timeout as my setting is to never timeout

Does anyone has an experience with that or an idea ?
Here is the postman console screenshot https://share.getcloudapp.com/geuWAmkl

**Comment by pinnacleapi** [comment]
Hi, pasted url https:// api.ps3838.com/v1/fixtures has space after https:// , can you check if that's what you have tested, if so please remove it and try again? Thanks.

**Comment by Eliakos** [comment]
Hi, someone from postman adviced me the same thing as you and it works now, silly error from me.
That was nice you took time to answer, thank you.

As i start the development of a robot to place bets on ps3838.com (i've been told it belongs to pinnacle and the API is the same) by using the Pinnacle API, i would like to know if the Pinnacle API will be maintained in the future or at least still be in place, so i can continue to use it. 

Do you have information on that ? (just to avoid develop a whole thing for nothing)

Thanks in advance.
