### ISSUE TITLE
Getting code INVALID_CREDENTIALS

### ISSUE THREAD

**Issue by patriczek** [pinnacleapi/pinnacleapi-documentation#28]
Hi, 

getting `{"code":"INVALID_CREDENTIALS","message":"Authorization failed, invalid credentials"}` but i'm pretty sure the credentials are correct, with the same creds i can make a log-in through web UI.

my CURL request:
`curl "https://api.pinnacle.com/v2/sports" -H 'Content-Type: application/json' -H 'Authorization: Basic login:pass' -H "X-Requested-With: XMLHttpRequest" -H "Accept: application/json"`

**Comment by charmingny** [comment]
did you use base64_encode(login:pass)?

**Comment by patriczek** [comment]
Yes i did. I followed documentation

**Comment by charmingny** [comment]
try adding "Content-length: 0"
and if it doesn't work try setting this.
CURLOPT_SSL_VERIFYPEER to false;

**Comment by patriczek** [comment]
Still doesn't work. In both cases i got `{"code":"INVALID_CREDENTIALS","message":"Authorization failed, invalid credentials"}`

**Comment by pinnacleapi** [comment]
Hi @patriczek , please contact Customer Support https://www.pinnacle.com/en/contact-us/

**Comment by patriczek** [comment]
> Hi @patriczek , please contact Customer Support https://www.pinnacle.com/en/contact-us/

Hi, thank you fast respond. Customer Support wrote me that, you doesn't offering api for public, and i have to contact B2B department.

**Comment by charmingny** [comment]
I think you just need to upload money and make some active bets. after that, you could test the API. when API is set, you can contact B2B for commercial purpose. 
For personal betting via API, you don't need to contact B2B but you need to be a active account ( meaning: you need to upload money and made some bets)

**Comment by patriczek** [comment]
Account is funded and also placed some bets, i get next email from CS and they wrote me:

`Dear Client,

Thank you for waiting.

Since we are no longer offering our API for free, all unauthorized access will eventually be blocked one by one.

If you would like to use our API, you may get in touch with the department in-charged at b2b@pinnaclesolution.com so they can provide you the commercial requirements.`

**Comment by cromat** [comment]
This is what I got for response regarding API:
```
Thank you for your interest with our betting API product.

We are offering our betting API to exclusive customers and partners at a monthly fee of USD5,000; alternatively, if you will be placing wagers to us though the API with a monthly volume of over USD250k, it can be offered free of charge.

You may find the API technical documents at https://github.com/pinnacleapi/pinnacleapi-documentation/blob/master/FAQ.md

Would you be able to advise us of your estimated monthly volume for us to assist you further?
```
