### ISSUE TITLE
Can Pinnacle Aisa site use the same api service ?

### ISSUE THREAD

**Issue by njwangchuan** [pinnacleapi/pinnacleapi-documentation#3]
I have use the api service for a long time and feel well.

Days ago I have received an email tell me my account would be trans to Asia region pinnacle888 on 08.02. I found the same api doc on pinnacle888 but can not use my authorization to access the service.

```
{
    "code": "INVALID_CREDENTIALS",
    "message": "Invalid username and password combination",
    "ref": null
}
```

Is it possible to use the service on the site pinnacle888, thanks

**Comment by pinnacleapi** [comment]
Please contact our B2B department for the API access 
b2b@pinnacle.com

**Comment by nietianqi** [comment]
pinnacle888 do not support api
