### ISSUE TITLE
Account not permitted to access the API

### ISSUE THREAD

**Issue by HoGarfield** [pinnacleapi/pinnacleapi-documentation#30]
I create account and funded, but still can not access the api with the error message "Account not permitted to access the API"

**Comment by pinnacleapi** [comment]
For the API access please contact our Pinnacle Solutions team 
https://www.pinnaclesolution.com

**Comment by PatrikBak** [comment]
@pinnacleapi Is this API still supported? I have the same problem, I contacted the support via https://www.pinnaclesolution.com/en/who-we-are/why-pinnacle/trusted-trading-expertise and have no response :(

**Comment by pinnacleapi** [comment]
@PatrikBak  we've passed on your query to the Pinnacle Solution team.

**Comment by LI-Jialu** [comment]
I contacted the solution team via https://www.pinnaclesolution.com/en/contact-us but got no response after 5 days, could you please kindly handle my request?
