### ISSUE TITLE
Error when placing bet for a baseball match

### ISSUE THREAD

**Issue by timecsvk** [pinnacleapi/pinnacleapi-documentation#31]
Hello,
when I place a bet for a baseball match with condition that pitcher must start  - please see the code below: 
PlaceBet(stake, sportId = 3, eventId, periodNumber = 0, lineId, pitcher1MustStart = TRUE, pitcher2MustStart = TRUE, betType = 'MONEYLINE', team = 'Team1', acceptBetterLine = TRUE, winRiskStake = "RISK", oddsFormat = "DECIMAL")

then I get this error: "Error in PlaceBet(stake, sportId = 3, eventId, periodNumber = 0, :unused argument (pitcher2MustStart = TRUE)"
 
I tried to change the script in many ways, but without any success and I still receive the error code related to unused argument for pitcherMustStart.
Can you help me to fix it?
 
Thank you.
Pedro

**Comment by pinnacleapi** [comment]
Apologies for the late response, this is kind of question is best to check with the customer support.
