### ISSUE TITLE
SPORT_ACCESS_DENIED

### ISSUE THREAD

**Issue by vateiixeira** [pinnacleapi/pinnacleapi-documentation#32]
My account is not allowed to access E Sport odds. How do I get permission to? I didn't find it in the documentation.

https://api.pinnacle.com/v1/odds?sportId=12

Resp:
{
    "code": "SPORT_ACCESS_DENIED",
    "message": "You are not authorized to access this sport"
}

**Comment by pinnacleapi** [comment]
Please check with the b2b support
