### ISSUE TITLE
Orphaned ParentId

### ISSUE THREAD

**Issue by bertinlosier** [pinnacleapi/pinnacleapi-documentation#33]
After getting fixtures for soccer, some of the resulting parentIds do not match an event Id in the soccer fixtures.

Am I missing something here, or is this expected?

If this is intentional, what should I do to eventually get the proper eventId and then "fix" these "orphaned" fixtures.

Regards,
Bertin

**Comment by pinnacleapi** [comment]
Hi Bertin, that should not be the case unless the match is already over. Do you have an example?
