### ISSUE TITLE
no puedo acceder 

### ISSUE THREAD

**Issue by gaf2419** [pinnacleapi/pinnacleapi-documentation#37]
![picture1](https://user-images.githubusercontent.com/47612753/108792932-6824ae80-7550-11eb-8492-e8ccb481093f.jpg)

I have tried to do the steps you indicate in your documentation but I cannot authenticate myself, and I have a balance in my pinnacle account, you can tell me how I can access.

**Comment by pinnacleapi** [comment]
If you still have the issue, please contact the support.
