### ISSUE TITLE
Id events changed for "pre" and "live"

### ISSUE THREAD

**Issue by bukosabino** [pinnacleapi/pinnacleapi-documentation#4]
Hi all, 

I would like to set some bets before the matches start. Then these bets would execute in "live", but the id events are changed when they start. So, what can I do? Is there any relation between events' identifiers for "pre" and "live"?

Thank you so much.

**Comment by pinnacleapi** [comment]
Hi  @bukosabino , please check [how to find associated events](https://github.com/pinnacleapi/pinnacleapi-documentation/blob/master/FAQ.md#how-to-find-associated-events).

**Comment by bukosabino** [comment]
Hi @pinnacleapi 

It's exactly what I need ^_^

Thank you
