### ISSUE TITLE
[Question] How to access the other odds?

### ISSUE THREAD

**Issue by appdev112** [pinnacleapi/pinnacleapi-documentation#43]
Hi,
Currently, I'm working with the Pinnacle football API.
I see that on the `/odds` endpoint, we can see some odds that have been served.
Can I access more odds on the API? Because, after a couple of hours of trying and reading all the documentation, I don't find any way to access other odds like:

- Double Chance
- Both Teams to Score
- Corners
- First Half
- etc

Is there any way to possibly access those odds?
Am I missing something here?
Thanks.

**Comment by heckad** [comment]
@appdev112 where do you find other odds?

**Comment by pinnacleapi** [comment]
Rest of the markets are offered as specials, see [faq](https://github.com/pinnacleapi/pinnacleapi-documentation/blob/master/FAQ.md#how-to-find-props-and-futures-markets) please.
