### ISSUE TITLE
Is there any calls number limit?

### ISSUE THREAD

**Issue by bukosabino** [pinnacleapi/pinnacleapi-documentation#5]
Hi all,

Is there any limit number of requests to API?

Thank you so much.

**Comment by pinnacleapi** [comment]
Hi @bukosabino , please see [fair use policy ](https://github.com/pinnacleapi/pinnacleapi-documentation/blob/master/FairUsePolicy.md)

**Comment by pinnacleapi** [comment]
Please follow [fair use policy ](https://github.com/pinnacleapi/pinnacleapi-documentation/blob/master/FairUsePolicy.md)
